on:
  push:
    branches:
      - master

name: Generate plots and aggregate metrics

jobs:
  generate_plots:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install -y libpng-dev
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v5
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
          R -e 'install.packages("purrr")'
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("svglite")'
          R -e 'install.packages("tidyr")'
          R -e 'install.packages("ggpubr")'
          R -e 'install.packages("gt")'
          R -e 'install.packages("gtExtras")'
          R -e 'install.packages("scales")'
      - name: Run R srcipt
        run: |
          mkdir -p plots/summary
          mkdir -p plots/timeline
          mkdir -p aggregated_data
          R < analytics.R --no-save

      - name: Add changed files
        run: |
          git checkout -b results
          git add aggregated_data plots
          git -c user.name=Bot -c user.email=dummy@example.com commit --message "Update plots"
          git push --set-upstream origin results --force
